//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yousef0523085
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TTask_ID { get; set; }
        public string Ttitle { get; set; }
        public string Tdescription { get; set; }
        public string Tstatues { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<int> TF_userid { get; set; }
    
        public virtual Userr Userr { get; set; }
    }
}
